site_name: drffrt
site_description: A Django Rest Framework for Redux Experimentation
repo_url: https://github.com/shearichard/drf-for-redux-testing
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/shearichard">shearichard</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
